export const SEARCH_FILM = 'SEARCH_FILM';
export const FILMS_HAS_ERRORED = 'FILMS_HAS_ERRORED';
export const FILMS_IS_LOADING = 'FILMS_IS_LOADING';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';