export const ADD_COMMENT = 'ADD_COMMENT';
export const IMAGES_HAS_ERRORED = 'IMAGES_HAS_ERRORED';
export const IMAGES_IS_LOADING = 'IMAGES_IS_LOADING';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const SET_FILM_RATING = 'SET_FILM_RATING';